/**
 *
 * $Id$
 */
package lintra.atlcompiler.javagen.validation;

import lintra.atlcompiler.javagen.JAttribute;
import lintra.atlcompiler.javagen.JMethod;

import lintra.atlcompiler.javagen.JType;
import lintra.atlcompiler.javagen.JTypeRef;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lintra.atlcompiler.javagen.JClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JClassValidator {
	boolean validate();

	boolean validateExtra(String value);
	boolean validatePkg(String value);
	boolean validateMethods(EList<JMethod> value);

	boolean validateAttributes(EList<JAttribute> value);

	boolean validateImplements(EList<JTypeRef> value);

	boolean validateImports(EList<JType> value);
}
